name: Bug Report
description: Report a bug or defect
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or error logs
      placeholder: Paste screenshots or logs here

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide relevant environment details
      placeholder: |
        - Browser: [e.g. Chrome 120]
        - OS: [e.g. macOS 14]
        - Node version: [e.g. 20.10]
        - Deployment: [e.g. local dev, staging, production]
      value: |
        - Browser:
        - OS:
        - Node version:
        - Deployment:

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - P0 - Critical (blocks release/production)
        - P1 - High (major functionality broken)
        - P2 - Medium (minor functionality affected)
      default: 2
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other relevant information
